services:
  api:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: test
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - .env.test
    volumes:
      - ./data/test/:/var/lib/postgresql/data